// ===== 일정 데이터 — 여기만 고치면 됩니다 =====
// 사진: images/ 폴더의 파일을 PHOTOS에서 영문이름(e:)으로 연결

const PHOTOS = {
 "Keflavík Airport": "images/keflavik-airport.jpg",
 "Seljalandsfoss": "images/seljalandsfoss.jpg",
 "Skógafoss": "images/skogafoss.jpg",
 "Kvernufoss": "images/kvernufoss.jpg",
 "Dyrhólaey": "images/dyrholaey.jpg",
 "Reynisfjara": "images/reynisfjara.jpg",
 "Landmannalaugar": "images/landmannalaugar.jpg",
 "Highland Center": "images/highland-center.jpg",
 "Brennisteinsalda": "images/brennisteinsalda.jpg",
 "Landmannalaugar Hot Spring": "images/landmannalaugar-hot-spring.jpg",
 "Háifoss": "images/haifoss.jpg",
 "Gullfoss": "images/gullfoss.jpg",
 "Kerlingarfjöll": "images/kerlingarfjoll.jpg",
 "Highland Base": "images/highland-base.jpg",
 "Hveravellir": "images/hveravellir.jpg",
 "Akureyri": "images/akureyri.jpg",
 "Goðafoss": "images/godafoss.jpg",
 "Dettifoss": "images/dettifoss.jpg",
 "Selfoss": "images/selfoss.jpg",
 "Egilsstaðir": "images/egilsstadir.png",
 "Hengifoss": "images/hengifoss.jpg",
 "Stuðlagil": "images/studlagil.jpg",
 "Vestrahorn / Stokksnes": "images/vestrahorn-stokksnes.jpg",
 "Höfn": "images/hofn.png",
 "Jökulsárlón": "images/jokulsarlon.jpg",
 "Diamond Beach": "images/diamond-beach.jpg",
 "Skaftafell": "images/skaftafell.jpg",
 "Svartifoss": "images/svartifoss.jpg",
 "Fjaðrárgljúfur": "images/fjadrargljufur.jpg",
 "Eldhraun": "images/eldhraun.jpg",
 "Reykjavík": "images/reykjavik.jpg",
 "Blue Lagoon": "images/blue-lagoon.jpg",
 "Sólheimajökull": "images/solheimajokull.jpg",
 "Hjörleifshöfði": "images/hjorleifshofdi.jpg",
 "Bláhnúkur": "images/blahnukur.jpg",
 "Vök Baths": "images/vok-baths.jpg",
 "Þakgil": "images/thakgil.jpg",
 "Suðurnámur": "images/sudurnamur.jpg",
 "Þverhamar": "images/thverhamar.jpg",
 "Múlagljúfur": "images/mulagljufur.jpg"
};

const DAYS = [
 { day:"7/1", title:"🏠 집 출발 → 인천공항 → ✈️ 코펜하겐 경유", color:"#808080", drive:"야간 비행 · 코펜하겐 경유", stay:"기내 (야간 비행)", flight:true,
   stops:[
     {n:"집 (서울)", e:"Home", gq:"Seoul", intl:true, t:"home", c:[37.5665,126.9780], note:"여정 시작 🏠"},
     {n:"인천공항 T2", e:"Incheon Airport", gq:"Incheon International Airport Terminal 2", intl:true, t:"airport", c:[37.4487,126.4505], note:"23:35 출발 · 제2터미널"},
     {n:"코펜하겐 공항 T3", e:"Copenhagen Airport", gq:"Copenhagen Airport", intl:true, t:"airport", c:[55.6180,12.6508], note:"익일 06:00 도착 · 제3터미널(경유)"},
   ],
   seg:[
     {f:"집",t:"인천공항 T2",d:"—",m:"~1h",note:"7/1 · 여유롭게 집결"},
     {f:"인천(ICN) 23:35",t:"코펜하겐(CPH) 06:00+1",d:"✈️",m:"13h25m",note:"제2터미널 출발"},
   ],
   trails:[] },

 { day:"7/2", title:"코펜하겐 ✈️ → KEF 도착 → 남부 폭포 → 솔헤이마요쿨 → Skógar", color:"#e6194B", drive:"운전 ~3h30m · 250km", stay:"Skógar Studio Apt (연박 1/2)",
   stops:[
     {n:"케플라비크 공항", e:"Keflavík Airport", t:"airport", c:[63.985,-22.605], w:["en:Keflavík International Airport"]},
     {n:"글류브라부이", e:"Gljúfrabúi", dr:"permit", drn:"셀야란즈포스 인접·군중, 사실상 불가", t:"spot", c:[63.6216,-19.9889], w:["en:Gljúfrabúi"], note:"셀야란즈포스 옆 ~600m · 절벽 틈 속 숨은 폭포 · 물 많이 튐(방수+방수신발)"},
     {n:"셀야란즈포스", e:"Seljalandsfoss", dr:"permit", drn:"군중·보호구역, 주간 사실상 불가", t:"spot", c:[63.6156,-19.9886], w:["en:Seljalandsfoss"], note:"폭포 뒤로 걸어 들어감 · 방수재킷"},
     {n:"스코가포스", e:"Skógafoss", dr:"no", drn:"보호구역, 허가 불가", t:"spot", c:[63.5320,-19.5114], w:["en:Skógafoss"]},
     {n:"크베르누포스", e:"Kvernufoss", dr:"ok", drn:"규정상 가능(군중 주의)", t:"spot", c:[63.5300,-19.4920], w:["is:Kvernufoss","en:Kvernufoss"], note:"Skógar 박물관 옆 주차→도보 15분, 숨은 명소"},
     {n:"솔헤이마요쿨 빙하", e:"Sólheimajökull", gq:"Sólheimajökull", dr:"ok", drn:"⭐드론 합법 최적지 — 공원·보호구역 밖, 일반규정만(아침/저녁 권장)", t:"spot", c:[63.5306,-19.3725], w:["en:Sólheimajökull"], note:"빙하 혀 도보 10~15분 · 빙하 드론 촬영 베스트"},
   ],
   seg:[
     {f:"코펜하겐(CPH) 08:20",t:"레이캬비크(KEF) 09:40",d:"✈️",m:"3h20m",note:"제3터미널 경유 환승"},
     {f:"공항",t:"글류브라부이",d:"176km",m:"2h15m"},
     {f:"→",t:"셀야란즈포스",d:"~0.6km 도보",m:"10m",note:"같은 주차장 · 북쪽에서 남쪽으로"},
     {f:"→",t:"스코가포스",d:"29km",m:"25m"},
     {f:"→",t:"크베르누포스",d:"3km+도보",m:"5m"},
     {f:"→",t:"솔헤이마요쿨(Road 221)",d:"12km",m:"15m"},
     {f:"→",t:"Skógar 숙소",d:"24km",m:"22m"},
   ],
   trails:[
     {nm:"스코가포스 — Skógá 강 '폭포길'(Waterfall Way)", st:"전망대만 왕복 ~15분 / 폭포구간(다리까지) 왕복 ~14~16km·5~7h / 풀코스 Skálabrekkufoss 왕복 26.2km·고도 1,131m·상급 [AllTrails]",
      ds:"스코가포스 동쪽 철계단을 올라 Skógá 강을 거슬러 오르면 협곡·현무암 사이로 20여 개 폭포가 줄지어 나옴(Fimmvörðuháls 트레일 초입). 아무 지점에서나 되돌아오면 됨.",
      tp:"💡 도착 첫날이라 무리 말고 계단 위 전망대~첫 폭포 몇 개까지(왕복 1~2h)만 가도 충분. 바람·비 대비 방수 레이어.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/skogafoss-skalabrekkufoss-waterfalls"},{t:"가이드",u:"https://adventures.is/blog/discover-the-skogafoss-waterfall-way-hike/"}]},
   ] },

 { day:"7/3", title:"샤크길 · Hjörleifshöfði(흑사장) · 레이니스피아라 · 디르홀레이", color:"#f58231", drive:"운전 ~2h35m · 135km", stay:"Skógar Studio Apt (연박 2/2)",
   stops:[
     {n:"샤크길", e:"Þakgil", dr:"ok", drn:"보호구역 아님(현장 확인)", t:"trail", c:[63.5167,-18.8500], w:["is:Þakgil"], note:"Road 214 비포장 자갈 · 천천히"},
     {n:"효를레이프스회프디 (흑사장)", e:"Hjörleifshöfði", gq:"Hjörleifshöfði", dr:"ok", drn:"보호구역 아님 — 일반규정(군중·바람·바닷가 주의)", t:"spot", c:[63.4178,-18.7616], w:["en:Hjörleifshöfði"], note:"검은 모래 곶 · Yoda Cave(요다 동굴) 명소"},
     {n:"레이니스피아라 흑사장", e:"Reynisfjara", dr:"no", drn:"안전·군중 금지", t:"spot", c:[63.4036,-19.0447], w:["en:Reynisfjara","en:Reynisdrangar"], note:"☠️ 너울(sneaker wave) 주의"},
     {n:"디르홀레이", e:"Dyrhólaey", dr:"no", drn:"조류 번식 보호구역", t:"spot", c:[63.4022,-19.1280], w:["en:Dyrhólaey"]},
   ],
   seg:[
     {f:"Skógar 숙소",t:"샤크길(Road214)",d:"~52km",m:"1h",note:"비포장 자갈"},
     {f:"→",t:"Hjörleifshöfði(흑사장)",d:"22km",m:"25m"},
     {f:"→",t:"레이니스피아라",d:"22km",m:"25m"},
     {f:"→",t:"디르홀레이",d:"10km",m:"15m"},
     {f:"→",t:"Skógar 숙소",d:"28km",m:"30m"},
   ],
   trails:[
     {nm:"Þakgil — ★1순위: Mýrdalsjökull 빙하 전망 루트", st:"≈13.8km 왕복(out-and-back) · 고도 648m · 5~5.5h · 중급 [AllTrails]",
      ds:"캠프장에서 꾸준히 오르며 Mýrdalsjökull 빙하 + Katla 화산 고원의 광활한 파노라마로 향하는 코스. 말발굽 모양 협곡 전망 포함 — Þakgil 빙하 뷰 하이라이트.",
      tp:"💡 등산 스틱 권장(후반 가파른 자갈 하산), 도하 1회(수위 따라) 주의, 오전 출발. 더 짧게는 빨강(Red) 루프에 빙하 전망 디투어(+~4km·1~1.5h)를 붙여도 됨.",
      links:[{t:"AllTrails(Mýrdalsjökull)",u:"https://www.alltrails.com/trail/iceland/southern/myrdalsjokull-glacier"},{t:"가이드(Red+빙하 디투어)",u:"https://thephotohikes.com/thakgil-red-trail-loop/"}]},
     {nm:"Þakgil — Remundargil 루프 (보라색)", st:"≈11km 루프 · 고도 752m · 5~5.5h · 상급(Hard) [AllTrails]",
      ds:"캠프장에서 강 따라 → 가파른 흙길 오르막 → Remundargil 협곡(Remundargilsfoss 폭포) → Kötlujökull(카틀라) 빙하 전망. 캠프장에 동굴 식당·온수 샤워. 세 색상 루프 중 가장 인기.",
      tp:"💡 등산 스틱 필수, 오전 출발. 짧게는 협곡 입구·동굴까지 ~3.8km(1h 미만) 쉬운 옵션. ⚠️ Vatnsrásarhöfuð 연장 변형은 '25 여름부터 일부 비공식 → 캠프장에서 현재 상태 확인. 매년 루트가 조금씩 바뀜.",
      links:[{t:"AllTrails(Remundargil)",u:"https://www.alltrails.com/trail/iceland/southern/thakgil-remundargil-vatnsrasarhofud"},{t:"가이드",u:"https://thephotohikes.com/thakgil-hiking-and-camping/"}]},
     {nm:"Þakgil — 빨강(Red) 루프 · Mælifell", st:"≈12.1km 루프 · 고도 603m · 4.5~5h · 상급(Hard) [AllTrails]",
      ds:"캠프장 → Miðfellshellir(미드펠 동굴, 옛 가을 양몰이 피난처) → Miðafrétt 능선 → Leynir 폭포 → Mælifell 정상(Mýrdalsjökull 빙하 파노라마) → Raufargil 협곡 동쪽 능선 → Barð 하산. 세 색상 루프 중 가장 험하고 경치 큼.",
      tp:"⚠️ 세 코스 중 가장 위험 — 좁고 노출된 칼날 능선 + 도하(river crossing) 3회. 우천·강풍 시 비추천, 등산화·스틱 필수.",
      links:[{t:"AllTrails(Mælifell)",u:"https://www.alltrails.com/trail/iceland/southern/thakgil-maelifell"},{t:"가이드(Red Trail)",u:"https://thephotohikes.com/thakgil-red-trail-loop/"}]},
     {nm:"Þakgil — 노랑(Yellow) 루프 · Austurafréttur", st:"≈16~17km 루프 · 고도 ~600m(추정) · 6~8h · 상급 [AllTrails]",
      ds:"세 코스 중 최장거리. Austurafréttur 산지 능선·계곡을 크게 도는 장거리 루프 — Mýrdalsjökull·Höfðabrekkuheiði 일대 광역 조망. 체력·시간 여유 있을 때만.",
      tp:"종일 코스 → 이른 출발 필수. 노랑 말뚝 표지. 캠프장 지도는 개략도라 오프라인 GPS 권장. (전체 대순환 변형은 AllTrails 기준 ≈19.6km·825m·6.5~7h)",
      links:[{t:"AllTrails(Red&Yellow)",u:"https://www.alltrails.com/trail/iceland/southern/thakgil-austurafrettur-red-and-yellow-trail"},{t:"후기(Yellow Route)",u:"https://blog.travelmarx.com/2015/07/akgil-thakgil-ausurafrettur-range-yello.html"}]},
   ] },

 { day:"7/4", title:"Vík → ⚠️F208 → 엘드가우 → 란드만 트레킹 ① → Highland Center", color:"#ffe119", drive:"운전 실제 ~5h · 180km", stay:"하이랜드 센터(확정)",
   stops:[
     {n:"엘드가우(Eldgjá)/오바이루포스", e:"Eldgjá", dr:"permit", drn:"Vatnajökull NP — 허가 필요", t:"trail", c:[63.967,-18.617], w:["en:Eldgjá","en:Ófærufoss"], note:"F208→F223 분기, 진입로 도하 1곳 · 폭포까지 왕복 2~2.5h(입구만 15~20분)"},
     {n:"란드만달라우가", e:"Landmannalaugar", dr:"no", drn:"❌ 불가 — Fjallabak 보호구역, 6/15~9/15 드론 전면 폐쇄·취미 허가 불가", t:"spot", c:[63.9836,-19.0608], w:["en:Landmannalaugar"]},
     {n:"수뒤르나뮈르 능선", e:"Suðurnámur", dr:"no", drn:"❌ 불가 — Fjallabak 보호구역, 6/15~9/15 드론 전면 폐쇄·취미 허가 불가", t:"trail", c:[64.0015,-19.0540], w:["en:Landmannalaugar"], note:"중간 코스(추천) — 분지 조망"},
     {n:"란드만 노천온천(Laugar)", e:"Landmannalaugar Hot Spring", t:"spring", c:[63.9840,-19.0560], w:["en:Landmannalaugar"], note:"무료·약 40°C · 트레킹 후 마무리"},
     {n:"하이랜드 센터(Hrauneyjar)", e:"Highland Center", t:"hotel", c:[64.179,-19.346], w:["is:Hrauneyjar"], note:"고지대 마지막 주유소 — 주유 필수"},
   ],
   seg:[
     {f:"Vík",t:"F208 남쪽 입구(포장)",d:"70km",m:"50m"},
     {f:"F208",t:"엘드가우(F223 분기)",d:"약 35km",m:"1h~1h30m",warn:true,note:"F223 진입로 ~3km·도하 1곳. 폭포 보면 +2~2.5h"},
     {f:"엘드가우",t:"란드만달라우가",d:"약 40km",m:"실제 1h30m~2h",warn:true,note:"도하 다수, 나머지 깊은 도하 구간"},
     {f:"→",t:"Highland Center",d:"37km",m:"45m~1h",note:"트레킹·온천 후 이동"},
   ],
   trails:[
     {nm:"엘드가우 협곡 — 오바이루포스(Ófærufoss)", st:"왕복 ≈2.5km(총거리) · 고도 ~80~216m · 40분~1.5h(여유 2h) · 쉬움~중급(평탄) [AllTrails]",
      ds:"세계 최대급 화산 열극협곡(길이 ~40km). 협곡 안쪽 2단 폭포 오바이루포스까지 강변 트레일, 도중 인도교로 도하. 입구·하단 전망만이면 15~20분.",
      tp:"💡 7/4가 이미 길어 시간 빠듯하면 입구 전망(15~20분)만. 폭포까지 가려면 왕복 2시간 확보. 공식 권장 체류 2~3h.",
      links:[{t:"공식(Vatnajökull NP)",u:"https://www.vatnajokulsthjodgardur.is/en"},{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/ofaerufoss"}]},
     {nm:"① 중간 코스 (추천) — 수뒤르나뮈르(Suðurnámur) 능선", st:"≈9.2km 루프 · 고도 451m · 3~3.5h · 중급 [AllTrails]",
      ds:"캠프 북쪽 F208 따라 1km → Námshraun 용암밭 가로질러 능선 2단 오르막. 분지 전체(Bláhnúkur·Brennisteinsalda·Grænagil·용암밭)를 내려다보는 조망형. 큰 스크리 하산 없고 위험 낮아 도착 피곤한 날에 적합.",
      tp:"💡 7/5 긴 코스와 지형이 거의 안 겹침(능선 위 vs 분지 안). 구름 낮으면 조망이 핵심이라 ↓ 대안 고려.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/landmannalaugar-haoldukvisl-sudurnamur"},{t:"공식(Fjallabak)",u:"https://ust.is/english/visiting-iceland/protected-areas/south/fjallabak-nature-reserve/outdoor-activities-and-hiking-trails/"}]},
     {nm:"대안 (악천후·매우 피곤) — Frostastaðavatn 호수 루프", st:"≈7.6km 루프 · 고도 361m · 2.5~3h · 중급 [AllTrails]",
      ds:"검은 용암밭에 둘러싸인 파란 호수 한 바퀴. 도하 없음, 부담 적고 7/5와 안 겹침.",
      tp:"♨️ 어느 코스든 끝나면 무료 노천온천(Laugar) 마무리 → Highland Center로 이동.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/landmannalaugar-frostastadavatn"}]},
   ],
   notice:"🚨 F208 = 가장 까다로운 구간. 4x4 필수·일반차 보험 미적용. 도하 전 차에서 내려 수심 확인, 1단 기어 저속. 출발 전 road.is로 개방 여부 필수 확인(남부 구간 6월말~7월초 개방)." },

 { day:"7/5", title:"란드만 트레킹 ② (긴 코스) → 하이포스 → Flúðir", color:"#bfef45", drive:"운전 ~4h · 180km · 도하 없음", stay:"Flúðir",
   stops:[
     {n:"Bláhnúkur(블라우흐누퀴르)", e:"Bláhnúkur", dr:"no", drn:"❌ 불가 — Fjallabak 보호구역, 6/15~9/15 드론 전면 폐쇄·취미 허가 불가", t:"trail", c:[63.9790,-19.0660], w:["en:Landmannalaugar"], note:"대순환 루프 — 940m 정상"},
     {n:"브레니스테인살다", e:"Brennisteinsalda", dr:"no", drn:"❌ 불가 — Fjallabak 보호구역, 6/15~9/15 드론 전면 폐쇄·취미 허가 불가", t:"trail", c:[63.974,-19.066], w:["en:Brennisteinsalda"], note:"대순환 루프에 포함(유황산)"},
     {n:"란드만 노천온천(Laugar)", e:"Landmannalaugar Hot Spring", t:"spring", c:[63.9840,-19.0560], w:["en:Landmannalaugar"], note:"무료·약 40°C, 출발 전 또는 후 소욕"},
     {n:"하이포스", e:"Háifoss", dr:"no", drn:"Þjórsárdalur 보호구역", t:"spot", c:[64.2122,-19.6886], w:["en:Háifoss"], note:"진입로 332 거침, 4x4"},
   ],
   seg:[
     {f:"하이랜드센터",t:"란드만(트레킹 재진입)",d:"37km",m:"45m~1h",note:"아침 복귀"},
     {f:"란드만",t:"하이포스",d:"95km",m:"2h+"},
     {f:"→",t:"Flúðir 숙소",d:"45km",m:"45m",note:"굴포스는 내일(7/6) 경유"},
   ],
   trails:[
     {nm:"② 긴 코스 (추천) — Bláhnúkur + Brennisteinsalda 대순환 루프", st:"≈10.6km 루프 · 고도 610m · 4~6h · 상급(Hard) [AllTrails]",
      ds:"캠프에서 강바닥 따라 Bláhnúkur(940m) 가파른 지그재그 정상 → 하산·개울 건너 Laugavegur 합류 → Brennisteinsalda(유황산) 정상 → Grænagil 협곡·Laugahraun 용암밭으로 하산. 두 정상+협곡+용암밭을 한 번에 도는 란드만 대표 데이하이크.",
      tp:"💡 마커 색이 자주 바뀌니 표지 주의. Bláhnúkur 초입 개울 건넘 · 7월 초 정상부 잔설 가능.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/landmannalaugar-blahnukur-brennisteinsalda"},{t:"Laugahraun 짧은 루프",u:"https://www.alltrails.com/trail/iceland/southern/landmannalaugar-short-loop"}]},
     {nm:"대안 (비·바람·Bláhnúkur 잔설 시)", st:"ⓐ Brennisteinsalda 방향만 ~4h (가파른 하산 회피)   ⓑ Laugavegur 초입~Stórihver 왕복 8~12km · 3~4.5h",
      ds:"Bláhnúkur 가파른 스크리 하산이 젖으면 위험. 날씨 나쁘면 Brennisteinsalda만 돌거나, Laugavegur 초입 지열지대(Stórihver)까지 왕복으로 전혀 다른 풍경.",
      tp:"⚠️ Skalli·Hrafntinnusker 방향은 7월 초 눈·길찾기 위험 → 비추천. 출발 전 safetravel.is·vedur.is 확인."},
   ],
   notice:"🥾 란드만 2일 트레킹 플랜 — 7/4 중간(수뒤르나뮈르 능선 조망) → 7/5 긴 코스(대순환 루프). 두 날 지형이 거의 안 겹치게 구성. 둘 다 무료 노천온천으로 마무리." },

 { day:"7/6", title:"굴포스 → ⚠️F35 → 컬링가프욜", color:"#3cb44b", drive:"운전 ~2h30m · 110km", stay:"highland base(확정)",
   stops:[
     {n:"굴포스", e:"Gullfoss", dr:"no", drn:"천연기념물, 허가 불가", t:"spot", c:[64.3271,-20.1199], w:["en:Gullfoss"], note:"F35 진입 직전 · 황금폭포 (동선상 우회 0)"},
     {n:"컬링가프욜", e:"Kerlingarfjöll", dr:"permit", drn:"보호경관·허가 필요(불확실)", t:"trail", c:[64.6379,-19.2939], w:["en:Kerlingarfjöll"]},
     {n:"Highland Base 온천", e:"Highland Base", t:"spring", c:[64.6333,-19.3000], w:["en:Kerlingarfjöll"], note:"♨️ 온천 일정 — 숙소(Highland Base) 내 온천, 트레킹 후 저녁 휴식"},
   ],
   seg:[
     {f:"Flúðir",t:"굴포스(F35입구,포장)",d:"40km",m:"35m"},
     {f:"굴포스",t:"컬링가프욜(F35)",d:"70km",m:"구글 1h30m / 실제 ~2h",warn:true,note:"자갈, 도하 없음·다리 완비"},
   ],
   trails:[
     {nm:"흐베라달리(Hveradalir) 지열지대", st:"≈3.5km 루프 · 고도 210m · 1~1.5h · 중급 [AllTrails]",
      ds:"아이슬란드 최대 고온 지열지대 — 적·황·녹 유문암 슬로프, 끓는 진흙, 증기 분출구.",
      tp:"💡 상단 주차장(Keis)이면 최소 오르막으로 핵심 접근. 하단은 더 풍성한 루프(내려갔다 다시 오르막). 지반 뜨거우니 마킹된 길만.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/hveradalir-loop"},{t:"공식 트레일가이드(PDF)",u:"https://www.ust.is/library/sida/Nattura/Kerlingarfjoll%20-%20trail%20guide.pdf"}]},
   ],
   notice:"F35는 F-road 중 가장 무난(도하 없음, 다리 완비)이나 자갈 노면이라 속도 못 냄." },

 { day:"7/7", title:"컬링가프욜 → ⚠️F35 → 아퀴레이리 → 후사비크 → 크로스달뤼르", color:"#42d4f4", drive:"운전 실제 6~7h · 약 370km · 종일 이동 + 후사비크 관광", stay:"크로스달뤼르(Kelduhverfi)",
   stops:[
     {n:"흐베라벨리르 온천", e:"Hveravellir", dr:"permit", drn:"자연보호구역(불확실)", t:"spring", c:[64.866,-19.566], w:["en:Hveravellir"], note:"F35 중간(절반 지점) 정차 추천"},
     {n:"아퀴레이리", e:"Akureyri", t:"spot", c:[65.6839,-18.1105], w:["en:Akureyri"], note:"경유 · 점심/주유/마트"},
     {n:"후사비크 시내", e:"Húsavík", t:"spot", c:[66.0449,-17.3389], w:["en:Húsavík"], note:"고래·퍼핀 투어 항구 마을 · 산책/식사"},
     {n:"GeoSea 바다 온천", e:"GeoSea Sea Baths", gq:"GeoSea Geothermal Sea Baths", t:"spring", c:[66.0552,-17.3460], w:["en:GeoSea"], note:"♨️(선택) 후사비크 등대 옆 절벽 바다온천 · 사전 예약 권장"},
     {n:"퍼핀 절벽 전망대 (Tjörnes)", e:"Tjörnes Cliff Viewpoint", gq:"Cliff Viewpoint Route 85 Iceland 66.1374,-16.9498", t:"spot", c:[66.1374,-16.9498], note:"🐧 후사비크→크로스달뤼르 Route 85 가는 길 · 퍼핀 관찰(여름 저녁 활발)"},
     {n:"크로스달뤼르 숙소", e:"Krossdalur", t:"hotel", c:[66.0556,-16.5800], note:"Krossdalur 2 2층 · Norðurþing 671 · 아스비르기 근처 (좌표 근사값)"},
   ],
   seg:[
     {f:"컬링가프욜",t:"아퀴레이리(F35→Route1)",d:"240km",m:"구글 4h / 실제 5h+",warn:true,note:"긴 자갈 주행. Blönduós에서 포장 합류"},
     {f:"아퀴레이리",t:"후사비크(Route1→85)",d:"75km",m:"1h"},
     {f:"후사비크",t:"크로스달뤼르(Route85·Tjörnes 경유)",d:"~55km",m:"45m",note:"퍼핀 절벽 지나 Kelduhverfi"},
   ],
   trails:[] },

 { day:"7/8", title:"크로스달뤼르 → 데티포스(동안→서안) → 셀포스 → 에이일스타디르", color:"#4363d8", drive:"운전 ~5h · 약 330km · 종일 이동 (자갈 Rd864 포함)", stay:"에이일스타디르",
   stops:[
     {n:"데티포스 (동안 East · Rd864)", e:"Dettifoss", dr:"no", drn:"Vatnajökull NP 드론 금지", t:"spot", c:[65.8160,-16.3790], w:["en:Dettifoss"], note:"⭐ 동안=폭포 정면 최강뷰 · 자갈(4WD 권장) · 북쪽 Rte85에서 진입해 남하 = backtrack 없음"},
     {n:"셀포스 (동안 East · Rd864)", e:"Selfoss", dr:"no", drn:"Vatnajökull NP 드론 금지", t:"spot", c:[65.8055,-16.3825], w:["en:Selfoss (waterfall)"], note:"동안 뷰가 훨씬 넓고 좋음(서안은 거의 뒷면) · 데티포스서 상류 도보 15~20분"},
     {n:"데티포스·셀포스 (서안 West · Rd862 포장)", e:"Dettifoss", dr:"no", drn:"Vatnajökull NP 드론 금지", t:"spot", c:[65.8147,-16.3884], w:["en:Dettifoss"], note:"포장·주차/화장실 완비 · Route1에서 왕복 · 측면 뷰 (시간 남으면)"},
     {n:"Vök Baths 온천", e:"Vök Baths", t:"spring", c:[65.3000,-14.4700], w:["en:Vök Baths","is:Vök Baths"], note:"♨️ 온천 일정 — 호수 위 떠 있는 노천탕, 도착 저녁 추천 · 사전 예약 권장"},
     {n:"에이일스타디르", e:"Egilsstaðir", t:"hotel", c:[65.2627,-14.3948], w:["en:Egilsstaðir"]},
   ],
   seg:[
     {f:"크로스달뤼르",t:"데티포스 동안(Rd864 진입)",d:"~55km",m:"1h",warn:true,note:"자갈 864 북쪽 진입 → 남하"},
     {f:"데티포스 동안",t:"셀포스 동안",d:"도보",m:"15~20m"},
     {f:"Rd864 남단",t:"데티포스 서안(Rd862 포장)",d:"~50km 왕복",m:"1h",note:"Route1 경유 서안 왕복 (선택)"},
     {f:"→",t:"에이일스타디르",d:"165km",m:"2h"},
   ],
   trails:[] },

 { day:"7/9", title:"헹기포스 → 슈트를라길 → 스톡스네스(저녁) → 회픈(Nypugardar)", color:"#911eb4", drive:"운전 ~6h · 약 400km · 긴 날", stay:"Guesthouse Nypugardar (Höfn)",
   stops:[
     {n:"헹기포스", e:"Hengifoss", dr:"ok", drn:"보호구역 아님", t:"trail", c:[65.0833,-14.8833], w:["en:Hengifoss"]},
     {n:"슈트를라길(동안 Klaustursel)", e:"Stuðlagil", dr:"ok", drn:"보호구역 아님(농지 예의)", t:"trail", c:[65.1411,-15.3266], w:["en:Stuðlagil"], note:"Road 923 후반 비포장"},
     {n:"베스트라혼 / 스톡스네스 (저녁)", e:"Vestrahorn / Stokksnes", dr:"permit", drn:"사유지 — Viking Café 허가받으면 가능", t:"spot", c:[64.2483,-14.9667], w:["en:Vestrahorn","en:Stokksnes"], note:"📷 반영샷 · Viking Café 입장료(~900 ISK) · 7/9 만조 22:26 → 21~23시 황혼+물 찬 모래 거울반영 (무풍일 때 최상)"},
     {n:"Guesthouse Nypugardar (Höfn)", e:"Höfn", gq:"Nypugardar 781 Hofn Iceland", t:"hotel", c:[64.2833,-15.2667], w:["en:Höfn"], note:"Nypugardar, 781 Höfn · 회픈 근처 · 스톡스네스 ~15km (좌표 근사값) · 🥐 조식 제공"},
   ],
   seg:[
     {f:"에이일스타디르",t:"헹기포스",d:"35km",m:"35m"},
     {f:"→",t:"슈트를라길(Klaustursel)",d:"50km",m:"50m"},
     {f:"슈트를라길",t:"스톡스네스(저녁)",d:"~285km",m:"3h40m",note:"에이일스타디르 거쳐 동부 피오르드 따라 남하"},
     {f:"스톡스네스",t:"Nypugardar 숙소(Höfn)",d:"~20km",m:"20m"},
   ],
   trails:[
     {nm:"헹기포스(Hengifoss)", st:"≈5.1km 왕복 · 고도 264m · 1.5~2h · 중급 [AllTrails]",
      ds:"중간 Litlanesfoss(주상절리 폭포) → 본 폭포 Hengifoss(128m, 빨간 점토층).",
      tp:"체력 부담 시 중간 폭포까지만 가도 가치 있음.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/eastern/hengifoss-waterfall"},{t:"공식(Visit Austurland)",u:"https://www.east.is/en/place/hengifoss"}]},
     {nm:"슈트를라길(Stuðlagil) — East Side", st:"하단주차 왕복 ≈9.7km·~2h / 상단 유료주차(≈1,000 ISK) 왕복 ~2~3km·30~40분 · 고도 ~20m(평탄)·쉬움 [AllTrails]",
      ds:"동안이 강 레벨에서 주상절리를 가까이 보는 핵심 뷰(서안은 위 전망대만). 청록 빙하강 + 육각 주상절리.",
      tp:"💡 왕복 포함 2~3h 확보. 한여름 수위 낮아 뷰 좋음.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/eastern/studlagil-canyon--2"},{t:"공식(Visit Austurland)",u:"https://www.east.is/en/place/studlagil-canyon"}]},
   ] },

 { day:"7/10", title:"회픈 → 요쿨살론 → 다이아몬드비치 → Múlagljúfur → 스카프타펠 → 프얄살론", color:"#f032e6", drive:"운전 ~4h30m · 약 290km · 긴 날", stay:"Skógar 근처",
   stops:[
     {n:"요쿨살론 빙하호", e:"Jökulsárlón", dr:"no", drn:"Vatnajökull NP — 7/15까지 번식기 폐쇄", t:"spot", c:[64.0784,-16.2306], w:["en:Jökulsárlón"]},
     {n:"다이아몬드 비치", e:"Diamond Beach", dr:"no", drn:"Vatnajökull NP — 7/15까지 폐쇄", t:"spot", c:[64.0440,-16.1790], w:["en:Breiðamerkursandur"]},
     {n:"Múlagljúfur 협곡", e:"Múlagljúfur", dr:"ok", drn:"공원 밖, 가능", t:"trail", c:[63.98918,-16.46942], w:["en:Múlagljúfur"], note:"⭐ 저장 목록에서 편입 — 숨은 협곡"},
     {n:"스카프타펠 (S6 트레킹)", e:"Skaftafell", dr:"no", drn:"Vatnajökull NP 금지", t:"trail", c:[64.0159,-16.9665], w:["en:Skaftafell"]},
     {n:"스바르티포스", e:"Svartifoss", dr:"no", drn:"Vatnajökull NP 금지", t:"spot", c:[64.0277,-16.9752], w:["en:Svartifoss"], note:"S6 코스 상에 위치"},
     {n:"프얄살론(Fjaðrárgljúfur)", e:"Fjaðrárgljúfur", dr:"no", drn:"보호구역, 허가 불가", t:"spot", c:[63.7714,-18.1722], w:["en:Fjaðrárgljúfur"]},
     {n:"엘드라운 이끼평원", e:"Eldhraun", dr:"permit", drn:"불확실 — 이끼 착륙 금지", t:"spot", c:[63.7500,-18.3000], w:["en:Eldhraun"], note:"Route1 변에서 감상 · 이끼 밟지 말 것"},
   ],
   seg:[
     {f:"Nypugardar(Höfn) 숙소",t:"요쿨살론",d:"80km",m:"1h",note:"링로드 서진"},
     {f:"요쿨살론",t:"Múlagljúfur 주차장",d:"22km",m:"20m"},
     {f:"→",t:"스카프타펠",d:"38km",m:"30m"},
     {f:"→",t:"프얄살론",d:"75km",m:"55m"},
     {f:"→",t:"엘드라운→Skógar",d:"70km",m:"55m"},
   ],
   trails:[
     {nm:"⭐ Múlagljúfur(물라글류퓌르) 협곡 트레킹", st:"≈7.1km 왕복(out-and-back) · 고도 ~386m · 2.5~3h · 중급(진흙·오르막) [AllTrails 기준]",
      ds:"주차장에서 오르막 트레일 따라 ~30~45분 → Hangandifoss 폭포와 이끼 협곡, Öræfajökull 빙하를 배경으로 한 절경 전망. 관광객 적은 숨은 명소.",
      tp:"💡 비 온 뒤 매우 질척임 → 방수 신발 필수. 가드레일 없으니 절벽 가장자리 주의. 스카프타펠 S6와 둘 다 하면 빡센 하루 → 컨디션 보고 택1 가능.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/eastern/hangandifoss-waterfall-mulagljufur-canyon"},{t:"가이드",u:"https://www.gocampers.is/nature/canyons/mulagljufur-canyon/"}]},
     {nm:"스카프타펠 S6 (Svartifoss → Sjónarnípa) ⭐추천", st:"≈7.6km · 고도 270m · 2~2.5h · 중급(공식: Challenging) [AllTrails]",
      ds:"이 한 코스로 스바르티포스(주상절리 폭포) + Sjónarnípa에서 Skaftafellsjökull 빙하·Öræfajökull 전망 둘 다 커버(=S1+S5 합본). 더 깊게는 S3(Skaftafellsheiði 대순환 16.6km·고도765m·5~6h)도 가치 있으나 시간 급증 → 물라글류퓌르와는 양립 어려움(택1). 짧게는 S1(스바르티포스만 왕복 ~3.7km·1~1.5h).",
      tp:"💡 비지터센터 주차장 오전 10시 전 도착(7월엔 오전 중 만차). ⚠️ S4(Kristínartindar 17.9km·6~8h)는 위험·비추천. 🌙 백야라도 저녁 트레킹 비추천 — 물라글류퓌르로 시간 빠듯하니 S6는 오후 이른 시간에 시작.",
      links:[{t:"AllTrails",u:"https://www.alltrails.com/trail/iceland/southern/sjonarnipa-svartifoss-magnusafoss-hundafoss-via-austurbrekkur"},{t:"공식 S6",u:"https://www.vatnajokulsthjodgardur.is/en/areas/skaftafell/svartifoss-sjonarnipa-s6"},{t:"공식 S5(Sjónarnípa)",u:"https://www.vatnajokulsthjodgardur.is/en/areas/skaftafell/sjonarnipa-s5"},{t:"공식 S3(대순환)",u:"https://www.vatnajokulsthjodgardur.is/en/areas/skaftafell/skaftafellsheidi-s3"}]},
   ] },

 { day:"7/11", title:"시내구경 → 블루라군", color:"#a9a9a9", drive:"운전 ~3h20m · 237km", stay:"Silica Hotel(레이캬비크)",
   stops:[
     {n:"레이캬비크 시내", e:"Reykjavík", dr:"permit", drn:"도심·공항구역 주의", t:"spot", c:[64.1466,-21.9426], w:["en:Reykjavík"], note:"🍴 Issi Fish & Chips"},
     {n:"블루라군", e:"Blue Lagoon", dr:"no", drn:"사유지·화산 TFR", t:"spring", c:[63.8804,-22.4495], w:["en:Blue Lagoon (geothermal spa)"], note:"사전 예약 필수 · Reykjanes 화산 상태 확인"},
   ],
   seg:[
     {f:"Vík/Skógar",t:"레이캬비크 시내",d:"187km",m:"2h30m"},
     {f:"→",t:"블루라군",d:"50km",m:"45~50m"},
     {f:"(참고)",t:"블루라군→KEF",d:"23km",m:"20m"},
   ],
   trails:[],
   notice:"🌋 용암/화산 — 2026.5 기준 분화는 없음(단 '분화 가능성 높음' 상태). 매일 vedur.is·safetravel.is·loftgaedi.is(가스) 확인, 분화 시 민방위(Almannavarnir) 지침 따라 관람. ▶ 상시 가능: Lava Show(레이캬비크/비크) · Inside the Volcano(7월 운영, 레이캬비크 근교 예약) · Raufarhólshellir 용암동굴 · 이미 일정의 엘드라운 용암밭." },

 { day:"7/12–13", title:"레이캬비크 출국 → ✈️ 코펜하겐 경유 → 서울 → 🏠 집", color:"#808080", drive:"KEF 10:30 출발 · 코펜하겐 경유", stay:"집 도착 (7/13)", flight:true,
   stops:[
     {n:"레이캬비크 (KEF)", e:"Keflavík Airport", gq:"Keflavík International Airport", t:"airport", c:[63.985,-22.605], note:"7/12 10:30 출발"},
     {n:"코펜하겐 공항 T3", e:"Copenhagen Airport", gq:"Copenhagen Airport", intl:true, t:"airport", c:[55.6180,12.6508], note:"15:35 도착 · 대기 8h20m · 23:55 재출발(경유)"},
     {n:"인천공항 T2", e:"Incheon Airport", gq:"Incheon International Airport Terminal 2", intl:true, t:"airport", c:[37.4487,126.4505], note:"7/13 18:35 도착 · 제2터미널"},
     {n:"집 (서울)", e:"Home", gq:"Seoul", intl:true, t:"home", c:[37.5665,126.9780], note:"여정 끝 🏠"},
   ],
   seg:[
     {f:"레이캬비크(KEF) 10:30",t:"코펜하겐(CPH) 15:35",d:"✈️",m:"3h5m",note:"제3터미널 도착"},
     {f:"코펜하겐 대기",t:"(환승)",d:"—",m:"8h20m",note:"15:35 → 23:55"},
     {f:"코펜하겐(CPH) 23:55",t:"서울(ICN) 18:35+1",d:"✈️",m:"11h40m",note:"7/13 인천 제2터미널 도착"},
     {f:"인천공항",t:"집",d:"—",m:"~1h",note:"🏠 여정 끝"},
   ],
   trails:[] },
];

const FAVORITES = [
 {n:"Gjáin (갸인)", c:[64.1873,-19.7039], cat:"near", note:"하이포스 옆 계곡 (7/5 근처)"},
 {n:"Svínafellsjökull 빙하", c:[64.0227,-16.80266], cat:"near", note:"스카프타펠 옆 (7/10)"},
 {n:"Forest Lagoon", c:[65.703,-18.083], cat:"near", note:"아퀴레이리 옆 숲속 온천 (7/7~8)"},
 {n:"Aldeyjarfoss", c:[65.3664,-17.337], cat:"near", note:"고다포스 남쪽 우회 ~1.5h (7/8)"},
 {n:"Granni 폭포", c:[65.359,-17.337], cat:"near", note:"Aldeyjarfoss 바로 옆 (7/8)"},
 {n:"Sky Lagoon", c:[64.11647,-21.94644], cat:"near", note:"레이캬비크 바닷가 온천 (7/11)"},
 {n:"Mælifell (마이리펠)", c:[63.7561,-18.7642], cat:"detour", note:"Mælifellssandur F210 하이랜드 별도 루트"},
 {n:"Askja (아스캬)", c:[65.03044,-16.74689], cat:"detour", note:"중앙 고원 깊숙이 · 종일 · 험한 F-road"},
 {n:"Kirkjufell (키르큐펠)", c:[64.93995,-23.30748], cat:"detour", note:"스나이펠스네스 반도"},
 {n:"Arnarstapi", c:[64.76673,-23.62808], cat:"detour", note:"스나이펠스네스 반도"},
 {n:"Hellnar", c:[64.75091,-23.64692], cat:"detour", note:"스나이펠스네스 반도"},
 {n:"Djúpalónssandur", c:[64.7521,-23.90322], cat:"detour", note:"스나이펠스네스 반도"},
 {n:"Ytri-Tunga", c:[64.8019,-23.0539], cat:"detour", note:"스나이펠스네스 물범 해변"},
 {n:"Barnafossar", c:[64.70182,-20.97367], cat:"detour", note:"서부 Borgarfjörður"},
 {n:"Dynjandi", c:[65.73251,-23.19856], cat:"detour", note:"베스트피오르드 (매우 멂)"},
 {n:"Hvítserkur", c:[65.6058,-20.6378], cat:"detour", note:"북부 Vatnsnes 반도 코뿔소바위"},
 {n:"Siglufjörður", c:[66.15049,-18.90963], cat:"detour", note:"북부 피오르드 마을"},
];

const LODGING = [
 {d:"7/2–3", n:"Skógar Studio Apartment", c:[63.52695,-19.49443], note:"Skógar (스코가포스 근처)"},
 {d:"7/4", n:"Highland Center (Hrauneyjar)", c:[64.179,-19.346], note:"확정", bf:1},
 {d:"7/5", n:"Efra-Sel, Flúðir", c:[64.14036,-20.36023], note:""},
 {d:"7/6", n:"Highland Base (Kerlingarfjöll)", c:[64.6333,-19.300], note:"확정", bf:1},
 {d:"7/7", n:"Krossdalur 2 (2층) · Kelduhverfi", c:[66.0556,-16.5800], note:"Krossdalur 2, 2nd floor, North Iceland, Norðurþing 671, Iceland · 후사비크 동쪽 ~50km, 아스비르기 근처 (좌표 근사값)"},
 {d:"7/8", n:"Studio Apartment Central (Egilsstaðir)", c:[65.25902,-14.3952], note:""},
 {d:"7/9", n:"Guesthouse Nypugardar (Höfn)", c:[64.2833,-15.2667], note:"Nypugardar, 781 Höfn, Iceland · 회픈 근처 · 스톡스네스 ~15km (좌표 근사값)", bf:1},
 {d:"7/10", n:"Mountain Queen Angelica (Drangshlíð)", c:[63.5269,-19.4470], note:"Skógar 근처"},
 {d:"7/11", n:"Silica Hotel", c:[63.88063,-22.44162], note:"⚠️ 레이캬비크 아님 — Blue Lagoon 옆", bf:1},
];
